"""baseline schema at the sqlite to postgres cutover

Revision ID: c6323e9b5e93
Revises: 
Create Date: 2026-08-29 23:09:03.210132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6323e9b5e93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_code'), ['code'], unique=True)

    op.create_table('decision_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_code', sa.String(length=50), nullable=False),
    sa.Column('decision_name_ar', sa.String(length=100), nullable=True),
    sa.Column('decision_name_en', sa.String(length=100), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_code')
    )
    op.create_table('defect_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=True),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_name', 'name_ar', name='uix_defect_reason_stage_ar'),
    sa.UniqueConstraint('stage_name', 'name_en', name='uix_defect_reason_stage_en')
    )
    with op.batch_alter_table('defect_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_reasons_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_reasons_stage_name'), ['stage_name'], unique=False)

    op.create_table('defect_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_code', sa.String(length=50), nullable=True),
    sa.Column('defect_name_ar', sa.String(length=100), nullable=False),
    sa.Column('defect_name_en', sa.String(length=100), nullable=True),
    sa.Column('applies_to_stages', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('element_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_code', sa.String(length=10), nullable=False),
    sa.Column('element_name', sa.String(length=50), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engineers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furnaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('furnace_code', sa.String(length=10), nullable=False),
    sa.Column('furnace_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('furnace_code')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=20), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_code')
    )
    op.create_table('molds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mold_number', sa.String(length=50), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('molds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_molds_diameter'), ['diameter'], unique=False)
        batch_op.create_index(batch_op.f('ix_molds_mold_number'), ['mold_number'], unique=True)

    op.create_table('non_conformance_actions',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('responsible', sa.String(length=120), nullable=True),
    sa.Column('responsible_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source', 'source_code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('screen', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'screen', 'action', name='uix_permission')
    )
    op.create_table('product_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_type', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('description_en', sa.String(length=200), nullable=True),
    sa.Column('description_ar', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('application_group', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_type', 'code', name='uix_param_type_code')
    )
    with op.batch_alter_table('product_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_parameters_param_type'), ['param_type'], unique=False)

    op.create_table('production_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('production_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_stages_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_stages_sort_order'), ['sort_order'], unique=False)

    op.create_table('reason_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_ar', name='uix_reason_name_ar'),
    sa.UniqueConstraint('name_en', name='uix_reason_name_en')
    )
    with op.batch_alter_table('reason_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reason_types_sort_order'), ['sort_order'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_number')
    )
    op.create_table('stage_decision_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('decision_name_en', sa.String(length=100), nullable=False),
    sa.Column('decision_name_ar', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_name', 'decision_name_ar', name='uix_stage_decision_ar'),
    sa.UniqueConstraint('stage_name', 'decision_name_en', name='uix_stage_decision_en')
    )
    with op.batch_alter_table('stage_decision_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_decision_types_stage_name'), ['stage_name'], unique=False)

    op.create_table('stage_defect_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('defect_name_en', sa.String(length=100), nullable=False),
    sa.Column('defect_name_ar', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_defect_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_defect_types_stage_name'), ['stage_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('full_name_ar', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_table_name'), ['table_name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_number', sa.String(length=50), nullable=False),
    sa.Column('sales_order', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_receipt', sa.String(length=100), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundles_bundle_number'), ['bundle_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bundles_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundles_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundles_sales_order'), ['sales_order'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('class_param_id', sa.Integer(), nullable=True),
    sa.Column('dn_param_id', sa.Integer(), nullable=True),
    sa.Column('zinc_type_param_id', sa.Integer(), nullable=True),
    sa.Column('length_param_id', sa.Integer(), nullable=True),
    sa.Column('pcs_stages_pass_param_id', sa.Integer(), nullable=True),
    sa.Column('internal_finish_param_id', sa.Integer(), nullable=True),
    sa.Column('external_finish_param_id', sa.Integer(), nullable=True),
    sa.Column('intent_use_param_id', sa.Integer(), nullable=True),
    sa.Column('project_type_param_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('application_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['dn_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['external_finish_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['intent_use_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['internal_finish_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['length_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['pcs_stages_pass_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['project_type_param_id'], ['product_parameters.id'], ),
    sa.ForeignKeyConstraint(['zinc_type_param_id'], ['product_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_code'), ['product_code'], unique=True)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_id', name='uix_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_role'), ['role'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_code', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('sales_number', sa.String(length=100), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('pipe_class', sa.String(length=20), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_weight', sa.Float(), nullable=True),
    sa.Column('product_length', sa.Float(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('application_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_orders_product_id'), ['product_id'], unique=False)

    op.create_table('chemical_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('furnace_id', sa.Integer(), nullable=True),
    sa.Column('ladle_no', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ladle_id', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('carbon', sa.Float(), nullable=True),
    sa.Column('silicon', sa.Float(), nullable=True),
    sa.Column('magnesium', sa.Float(), nullable=True),
    sa.Column('copper', sa.Float(), nullable=True),
    sa.Column('chromium', sa.Float(), nullable=True),
    sa.Column('sulfur', sa.Float(), nullable=True),
    sa.Column('manganese', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('lead', sa.Float(), nullable=True),
    sa.Column('aluminum', sa.Float(), nullable=True),
    sa.Column('carbon_equivalent', sa.Float(), nullable=True),
    sa.Column('manganese_equivalent', sa.Float(), nullable=True),
    sa.Column('magnesium_equivalent', sa.Float(), nullable=True),
    sa.Column('engineer_notes', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('has_defect', sa.Boolean(), nullable=True),
    sa.Column('defect_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['furnace_id'], ['furnaces.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chemical_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_analyses_ladle_id'), ['ladle_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chemical_analyses_production_order_id'), ['production_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_analyses_test_date'), ['test_date'], unique=False)

    op.create_table('pipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Integer(), nullable=True),
    sa.Column('shift_engineer', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_order', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('pipe_code', sa.String(length=50), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('pipe_class', sa.String(length=20), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('mold_number', sa.String(length=20), nullable=True),
    sa.Column('iso_weight', sa.Float(), nullable=True),
    sa.Column('no_code', sa.String(length=50), nullable=True),
    sa.Column('arrange_pipe', sa.Integer(), nullable=True),
    sa.Column('warehouse_barcode', sa.String(length=32), nullable=True),
    sa.Column('ladle_id', sa.String(length=20), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('thickness_socket_2', sa.Float(), nullable=True),
    sa.Column('thickness_spigot', sa.Float(), nullable=True),
    sa.Column('thickness_spigot_2', sa.Float(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('mechanical_test_role', sa.String(length=20), nullable=True),
    sa.Column('lab_decision', sa.String(length=20), nullable=True),
    sa.Column('lab_decision_reason', sa.Text(), nullable=True),
    sa.Column('cascade_from', sa.String(length=100), nullable=True),
    sa.Column('final_decision_value', sa.String(length=20), nullable=True),
    sa.Column('final_decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ladle_id'], ['chemical_analyses.ladle_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipes_final_decision_value'), ['final_decision_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipes_no_code'), ['no_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipes_production_date'), ['production_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipes_production_order_id'), ['production_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipes_warehouse_barcode'), ['warehouse_barcode'], unique=True)

    op.create_table('mechanical_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_number', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('pipe_code', sa.String(length=100), nullable=True),
    sa.Column('pipe_no', sa.Integer(), nullable=True),
    sa.Column('ladle_id', sa.String(length=20), nullable=True),
    sa.Column('pipe_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sample_thickness', sa.Float(), nullable=True),
    sa.Column('d1', sa.Float(), nullable=True),
    sa.Column('d2', sa.Float(), nullable=True),
    sa.Column('d3', sa.Float(), nullable=True),
    sa.Column('avg_dimension', sa.Float(), nullable=True),
    sa.Column('original_length', sa.Float(), nullable=True),
    sa.Column('final_length', sa.Float(), nullable=True),
    sa.Column('area_d_squared', sa.Float(), nullable=True),
    sa.Column('force_kgf', sa.Float(), nullable=True),
    sa.Column('tensile_strength', sa.Float(), nullable=True),
    sa.Column('elongation', sa.Float(), nullable=True),
    sa.Column('microstructure', sa.Text(), nullable=True),
    sa.Column('percent_85', sa.Float(), nullable=True),
    sa.Column('percent_70', sa.Float(), nullable=True),
    sa.Column('percent_40', sa.Float(), nullable=True),
    sa.Column('percent_1', sa.Float(), nullable=True),
    sa.Column('nodularity_percent', sa.Float(), nullable=True),
    sa.Column('nodule_count', sa.Integer(), nullable=True),
    sa.Column('hardness', sa.Float(), nullable=True),
    sa.Column('carbides', sa.Float(), nullable=True),
    sa.Column('tensile_mpa', sa.Float(), nullable=True),
    sa.Column('image_as_polished', sa.String(length=255), nullable=True),
    sa.Column('image_etched', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retest_reason', sa.Text(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('original_test_id', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Integer(), nullable=True),
    sa.Column('tester_name', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('has_defect', sa.Boolean(), nullable=True),
    sa.Column('defect_reason', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ladle_id'], ['chemical_analyses.ladle_id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_test_id'], ['mechanical_tests.id'], ),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['mechanical_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mechanical_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mechanical_tests_ladle_id'), ['ladle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mechanical_tests_pipe_code'), ['pipe_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mechanical_tests_pipe_id'), ['pipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mechanical_tests_test_date'), ['test_date'], unique=False)

    op.create_table('pipe_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('stage_date', sa.Date(), nullable=True),
    sa.Column('stage_time', sa.Time(), nullable=True),
    sa.Column('measurement_value', sa.Float(), nullable=True),
    sa.Column('measurement_type', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('has_defect', sa.Boolean(), nullable=True),
    sa.Column('defect_type_id', sa.Integer(), nullable=True),
    sa.Column('defect_type', sa.String(length=100), nullable=True),
    sa.Column('defect_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('thickness_socket', sa.Float(), nullable=True),
    sa.Column('thickness_spigot', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('thickness_profile', sa.JSON(), nullable=True),
    sa.Column('dimension_profile', sa.JSON(), nullable=True),
    sa.Column('ovality_profile', sa.JSON(), nullable=True),
    sa.Column('visual_profile', sa.JSON(), nullable=True),
    sa.Column('zinc_profile', sa.JSON(), nullable=True),
    sa.Column('ring_profile', sa.JSON(), nullable=True),
    sa.Column('shift_responsible', sa.String(length=100), nullable=True),
    sa.Column('sales_order', sa.String(length=100), nullable=True),
    sa.Column('delivery_customer', sa.String(length=200), nullable=True),
    sa.Column('delivery_receipt', sa.String(length=100), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('bundle_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_types.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipe_id', 'stage_name', name='uix_pipe_stage')
    )
    op.create_table('pipe_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipe_stage_id', sa.Integer(), nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('machine_code', sa.String(length=20), nullable=True),
    sa.Column('has_defect', sa.Boolean(), nullable=True),
    sa.Column('defect_type', sa.String(length=100), nullable=True),
    sa.Column('defect_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('measurement_value', sa.Float(), nullable=True),
    sa.Column('measurement_type', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('stage_date', sa.Date(), nullable=True),
    sa.Column('stage_time', sa.Time(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ),
    sa.ForeignKeyConstraint(['pipe_stage_id'], ['pipe_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipe_stage_history')
    op.drop_table('pipe_stages')
    with op.batch_alter_table('mechanical_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mechanical_tests_test_date'))
        batch_op.drop_index(batch_op.f('ix_mechanical_tests_pipe_id'))
        batch_op.drop_index(batch_op.f('ix_mechanical_tests_pipe_code'))
        batch_op.drop_index(batch_op.f('ix_mechanical_tests_ladle_id'))

    op.drop_table('mechanical_tests')
    with op.batch_alter_table('pipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipes_warehouse_barcode'))
        batch_op.drop_index(batch_op.f('ix_pipes_production_order_id'))
        batch_op.drop_index(batch_op.f('ix_pipes_production_date'))
        batch_op.drop_index(batch_op.f('ix_pipes_product_id'))
        batch_op.drop_index(batch_op.f('ix_pipes_no_code'))
        batch_op.drop_index(batch_op.f('ix_pipes_final_decision_value'))

    op.drop_table('pipes')
    with op.batch_alter_table('chemical_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_analyses_test_date'))
        batch_op.drop_index(batch_op.f('ix_chemical_analyses_production_order_id'))
        batch_op.drop_index(batch_op.f('ix_chemical_analyses_ladle_id'))

    op.drop_table('chemical_analyses')
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_production_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_production_orders_customer_id'))

    op.drop_table('production_orders')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_code'))

    op.drop_table('products')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_created_at'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundles_sales_order'))
        batch_op.drop_index(batch_op.f('ix_bundles_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_bundles_customer_id'))
        batch_op.drop_index(batch_op.f('ix_bundles_bundle_number'))

    op.drop_table('bundles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_record_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_table_name'))
        batch_op.drop_index(batch_op.f('ix_attachments_record_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('stage_defect_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_defect_types_stage_name'))

    op.drop_table('stage_defect_types')
    with op.batch_alter_table('stage_decision_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_decision_types_stage_name'))

    op.drop_table('stage_decision_types')
    op.drop_table('shifts')
    with op.batch_alter_table('reason_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reason_types_sort_order'))

    op.drop_table('reason_types')
    with op.batch_alter_table('production_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_stages_sort_order'))
        batch_op.drop_index(batch_op.f('ix_production_stages_code'))

    op.drop_table('production_stages')
    with op.batch_alter_table('product_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_parameters_param_type'))

    op.drop_table('product_parameters')
    op.drop_table('permissions')
    op.drop_table('non_conformance_actions')
    with op.batch_alter_table('molds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_molds_mold_number'))
        batch_op.drop_index(batch_op.f('ix_molds_diameter'))

    op.drop_table('molds')
    op.drop_table('machines')
    op.drop_table('furnaces')
    op.drop_table('engineers')
    op.drop_table('element_specifications')
    op.drop_table('defect_types')
    with op.batch_alter_table('defect_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_reasons_stage_name'))
        batch_op.drop_index(batch_op.f('ix_defect_reasons_sort_order'))

    op.drop_table('defect_reasons')
    op.drop_table('decision_types')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_code'))

    op.drop_table('customers')
    # ### end Alembic commands ###
