"""Annealing batch # is system-generated (ANN-YYYYMMDD-N); the Annealing
date/time are editable (operator may backdate an entry) and default to
today/now when left blank.

Semantics (updated 2026-08-09 per client request — manual entry was
previously ignored, which blocked backdated registrations):
  - New Annealing entry, no date/time posted → batch = next ANN-<today>-N,
    date = today, time = now
  - Posted date/time are honored; the batch prefix follows the posted date
  - Posted batch numbers are always ignored (server is truth)
  - Re-saving without date/time never renumbers or re-stamps
"""

import re
import unittest
from datetime import date

from app import create_app, db
from app.models.permission import seed_default_permissions
from app.models.pipe import Pipe, PipeStage
from app.models.user import User
from app.routes.stages import next_annealing_batch


class AnnealingAutoBatchTestCase(unittest.TestCase):
    def setUp(self):
        self.app = create_app("testing")
        self.app.config["WTF_CSRF_ENABLED"] = False
        self.ctx = self.app.app_context()
        self.ctx.push()
        db.drop_all()
        db.create_all()
        seed_default_permissions()
        self.client = self.app.test_client()

        u = User(username="admin", full_name="Admin", role="admin", is_active=True)
        u.set_password("x")
        db.session.add(u)
        db.session.commit()
        self.user_id = u.id

    def tearDown(self):
        db.session.remove()
        db.drop_all()
        self.ctx.pop()

    def _login(self):
        with self.client.session_transaction() as sess:
            sess["_user_id"] = str(self.user_id)
            sess["_fresh"] = True

    def _pipe(self, no_code):
        p = Pipe(
            production_date=date(2026, 4, 14), ladle_id="G1",
            pipe_code=no_code, no_code=no_code, arrange_pipe=1,
            diameter=300, pipe_class="K9",
        )
        db.session.add(p)
        db.session.commit()
        return p

    def _post_edit(self, pipe, **fields):
        base = {
            "no_code": pipe.no_code, "production_date": "2026-04-14",
            "shift": "1", "diameter": "300", "pipe_class": "K9",
            "arrange_pipe": "1",
        }
        base.update(fields)
        return self.client.post(f"/stages/{pipe.id}/edit", data=base)

    def _annealing(self, pipe):
        return PipeStage.query.filter_by(
            pipe_id=pipe.id, stage_name="Annealing"
        ).first()

    # --- numbering --------------------------------------------------------

    def test_batch_format_is_date_based(self):
        batch = next_annealing_batch()
        self.assertRegex(batch, rf"^ANN-{date.today():%Y%m%d}-1$")

    def test_batch_increments_within_a_day(self):
        p1 = self._pipe("N0001")
        db.session.add(PipeStage(
            pipe_id=p1.id, stage_name="Annealing",
            bundle_number=next_annealing_batch(),
        ))
        db.session.commit()
        self.assertTrue(next_annealing_batch().endswith("-2"))

    def test_batch_ignores_foreign_prefixes(self):
        p1 = self._pipe("N0001")
        db.session.add(PipeStage(
            pipe_id=p1.id, stage_name="Annealing", bundle_number="1200",
        ))
        db.session.commit()
        self.assertTrue(next_annealing_batch().endswith("-1"))

    # --- edit form ---------------------------------------------------------

    def test_edit_honors_posted_datetime_batch_stays_auto(self):
        self._login()
        p = self._pipe("N0001")
        resp = self._post_edit(
            p,
            stage_Annealing_decision="Accept",
            # posted batch must be ignored; posted date/time must be honored
            stage_Annealing_batch_number="FAKE",
            stage_Annealing_date="2026-07-15",
            stage_Annealing_time="03:04",
        )
        self.assertEqual(resp.status_code, 302, resp.get_data(as_text=True))

        stage = self._annealing(p)
        self.assertIsNotNone(stage)
        # batch prefix follows the POSTED date, sequence generated by server
        self.assertRegex(stage.bundle_number, r"^ANN-20260715-1$")
        self.assertEqual(stage.stage_date, date(2026, 7, 15))
        self.assertEqual(
            (stage.stage_time.hour, stage.stage_time.minute), (3, 4)
        )

    def test_edit_blank_datetime_falls_back_to_system_stamp(self):
        self._login()
        p = self._pipe("N0001")
        resp = self._post_edit(p, stage_Annealing_decision="Accept")
        self.assertEqual(resp.status_code, 302, resp.get_data(as_text=True))

        stage = self._annealing(p)
        self.assertIsNotNone(stage)
        self.assertRegex(stage.bundle_number, rf"^ANN-{date.today():%Y%m%d}-1$")
        self.assertEqual(stage.stage_date, date.today())
        self.assertIsNotNone(stage.stage_time)

    def test_edit_resave_never_renumbers(self):
        self._login()
        p = self._pipe("N0001")
        self._post_edit(p, stage_Annealing_decision="Accept")
        first = self._annealing(p)
        batch, sdate, stime = (
            first.bundle_number, first.stage_date, first.stage_time,
        )

        self._post_edit(p, stage_Annealing_decision="Hold")
        second = self._annealing(p)
        self.assertEqual(second.decision, "Hold")
        self.assertEqual(
            (second.bundle_number, second.stage_date, second.stage_time),
            (batch, sdate, stime),
        )

    def test_two_pipes_same_day_get_sequential_batches(self):
        self._login()
        p1, p2 = self._pipe("N0001"), self._pipe("N0002")
        self._post_edit(p1, stage_Annealing_decision="Accept")
        self._post_edit(p2, stage_Annealing_decision="Accept")
        b1 = self._annealing(p1).bundle_number
        b2 = self._annealing(p2).bundle_number
        self.assertTrue(b1.endswith("-1"), b1)
        self.assertTrue(b2.endswith("-2"), b2)

    def test_edit_form_annealing_inputs_are_editable_batch_readonly(self):
        self._login()
        p = self._pipe("N0001")
        html = self.client.get(f"/stages/{p.id}/edit").get_data(as_text=True)
        date_block = re.search(
            r'<input type="date" name="stage_Annealing_date"[^>]*>', html,
        )
        time_block = re.search(
            r'<input type="time" name="stage_Annealing_time"[^>]*>', html,
        )
        batch_block = re.search(
            r'<input type="text" name="stage_Annealing_batch_number"[^>]*>', html,
        )
        self.assertIsNotNone(date_block)
        self.assertIsNotNone(time_block)
        self.assertIsNotNone(batch_block)
        # date/time editable (manual backdating); batch stays server-generated
        self.assertNotIn("readonly", date_block.group(0))
        self.assertNotIn("readonly", time_block.group(0))
        self.assertIn("readonly", batch_block.group(0))

    def test_forms_do_not_prefill_annealing_datetime(self):
        # DrAlaa 2026-08-10: a JS prefill made every pipe look like it had
        # already entered Annealing (date/time auto-set to now, batch
        # generated from it). The inputs must render EMPTY and no script may
        # fill them — the batch only appears after manual entry.
        self._login()
        p = self._pipe("N0001")
        for url in ("/stages/add", f"/stages/{p.id}/edit"):
            html = self.client.get(url).get_data(as_text=True)
            self.assertNotIn("annealing-auto-date", html, url)
            self.assertNotIn("annealing-auto-time", html, url)
            date_block = re.search(
                r'<input type="date" name="stage_Annealing_date"[^>]*>', html,
            )
            self.assertIsNotNone(date_block, url)
            self.assertNotRegex(date_block.group(0), r'value="\d', url)

    # --- update_stage (console / modal) ------------------------------------

    def test_update_stage_honors_posted_datetime_batch_stays_auto(self):
        self._login()
        p = self._pipe("N0001")
        resp = self.client.post(
            f"/stages/{p.id}/stage/Annealing",
            json={
                "decision": "Accept",
                "bundle_number": "FAKE",
                "stage_date": "2001-01-01",
                "stage_time": "03:04",
            },
        )
        self.assertTrue(resp.get_json()["success"], resp.get_data(as_text=True))
        stage = self._annealing(p)
        # posted date/time honored; batch prefix follows the posted date
        self.assertRegex(stage.bundle_number, r"^ANN-20010101-1$")
        self.assertEqual(stage.stage_date, date(2001, 1, 1))
        self.assertEqual(
            (stage.stage_time.hour, stage.stage_time.minute), (3, 4)
        )

    def test_update_stage_blank_datetime_falls_back_to_system_stamp(self):
        self._login()
        p = self._pipe("N0001")
        resp = self.client.post(
            f"/stages/{p.id}/stage/Annealing", json={"decision": "Accept"}
        )
        self.assertTrue(resp.get_json()["success"], resp.get_data(as_text=True))
        stage = self._annealing(p)
        self.assertRegex(stage.bundle_number, rf"^ANN-{date.today():%Y%m%d}-1$")
        self.assertEqual(stage.stage_date, date.today())
        self.assertIsNotNone(stage.stage_time)

    def test_update_stage_resave_preserves_stamp(self):
        self._login()
        p = self._pipe("N0001")
        self.client.post(
            f"/stages/{p.id}/stage/Annealing", json={"decision": "Accept"}
        )
        first = self._annealing(p)
        self.client.post(
            f"/stages/{p.id}/stage/Annealing",
            json={"notes": "checked", "bundle_number": "FAKE"},
        )
        second = self._annealing(p)
        self.assertEqual(second.bundle_number, first.bundle_number)
        self.assertEqual(second.stage_date, first.stage_date)
        self.assertEqual(second.stage_time, first.stage_time)
        self.assertEqual(second.notes, "checked")


if __name__ == "__main__":
    unittest.main()
